use_frameworks!

platform :ios, '9.0'

target 'ninePatchImage_Example' do
  pod 'ninePatchImage', :path => '../'

  target 'ninePatchImage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
